version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:1.0-2.0
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Docker Compose
          command: docker-compose  -f "C:\GitHub\net-core-api-cd\docker-compose.yml" -f "C:\GitHub\net-core-api-cd\docker-compose.override.yml" -f "C:\GitHub\net-core-api-cd\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose2862132963656988669 up -d --force-recreate --remove-orphans