version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:1.0-2.0
      
    working_directory: ~/repo

    steps:
      - checkout
      
      - run: dotnet restore
      - run: dotnet build
          