version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    working_directory: ~/repo

    steps:
      - checkout
      
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test DockerNetCore.Tests/
      - run: dotnet publish DockerNetCore.Api/DockerNetCore.Api.csproj -c Release -f netcoreapp2.0          
      - setup_remote_docker

      - run: |
          # This approach feels faster then the provided as example on Docker website using multi-staged builds.
          # https://docs.docker.com/engine/examples/dotnetcore/
          
          cp DockerNetCore.Api/Dockerfile DockerNetCore.Api/bin/Release/netcoreapp2.0/publish/