version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    working_directory: ~/repo

    steps:
      - checkout
      
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test DockerNetCore.Tests/
          