version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: NUnit Tests
          command: dotnet build DockerNetCore.Api.sln